### PR TITLE
feat: Add support for Notion hackerpack pages + subpages

### PR DESCRIPTION
**Pull request by MichaelZhao21**
Features are done (just cherry-picking from main hackportal PR and fixing CSS issues), but the Notion page is not. Don't push until experience finishes writing hackerpack docs.

### CODE REVIEW

**Comment by MichaelZhao21** [comment]
Update: I need to fix mobile

**Comment by abdullah50053** [comment]
Screen Shot 2022-10-25 at 10 44 35 PM
Fix rotated mobile view

**Comment by MichaelZhao21** [comment]
Do you think we should just get rid of that sidebar? Or I can just add a scrolling behavior on it

**Comment by abdullah50053** [comment]
lgtm. mark as ready when the hackerpack is complete

**Review by abdullah50053 — APPROVED** [review]

**Pull request merged**
