### PR TITLE
feat: Restyle HackUTD IX site

### PR DESCRIPTION
**Pull request by abdullah50053**
Home, login, and registration page styling

### CODE REVIEW

**Comment by abdullah50053** [comment]
- [x] Hide all pages except Home and Registration
- [x] Fix: Nav bar overlaps the jumbotron on web:
Screen Shot 2022-07-29 at 6 37 25 PM

- [ ] Fix: Nav bar overlaps Big Header on mobile hackerpack and schedule (Can be a separate PR):
Screen Shot 2022-07-29 at 6 38 35 PM
Screen Shot 2022-07-29 at 6 39 14 PM

- [x] Add asset - Pluto character 
- [x] FIx white bar on the bottom of the screen 
Screen Shot 2022-07-29 at 6 41 51 PM

- [x] Change profile card background color 
Screen Shot 2022-07-29 at 6 45 34 PM

- [x] Don't let hackers select a custom university or major
Screen Shot 2022-07-29 at 6 47 54 PM

- [x] Change
Screen Shot 2022-07-29 at 6 49 02 PM

**Comment by nam-t24** [comment]
For the custom univ and major, I set it to allow custom because the search dropdown works a lot better with it and I think there are some private colleges nearby that aren't on the list like Austin College(I added myself). Also high schoolers could apply I think so maybe they can add their high school as custom option. But if setting it to hard limit those colleges with an "other" option would be better then I can still implement it.

**Comment by nam-t24** [comment]
I went ahead and removed custom options but if you want to remove some universities/majors to make it more navigable feel free to do that

**Comment by abdullah50053** [comment]
- [x] Reduce spacing between About header and content
Screen Shot 2022-08-06 at 6 52 01 PM

- [x] Add rocket graphic 
- [ ] Add other background graphics (see Figma)
Screen Shot 2022-08-06 at 6 53 15 PM

**Pull request merged**
